# Generated by Django 3.1.3 on 2020-11-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20201114_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
